In [9]:
# import required libraries
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import math

In [27]:
# loading the data
import csv

with open('train.csv', newline='') as csvfile:
    data = list(csv.reader(csvfile))
    

data_x = [[int(x) for x in row[1:]] for row in data[1:]]
data_y = [[0 if i != int(row[0]) else 1 for i in range(10)] for row in data[1:]]

In [28]:
# randomizing the data

# splitting into test and train
train_percent = 0.8

cutoff = math.floor(len(data) * train_percent)
X_train = np.array(data_x[:cutoff])
Y_train = np.array(data_y[:cutoff])
X_test = np.array(data_x[cutoff:])
Y_test = np.array(data_y[cutoff:])
print(X_train[:2])
print(Y_train[:2])


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [29]:
# normalize the X data
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [30]:
# building out the model
model = keras.models.Sequential()

# adding the first hidden layer
model.add(layers.Dense(512, input_shape=(784,)))
model.add(layers.Activation('relu'))                            
model.add(layers.Dropout(0.2))

# adding the second hidden layer
model.add(layers.Dense(512))
model.add(layers.Activation('relu'))
model.add(layers.Dropout(0.2))

# adding the output layer
model.add(layers.Dense(10))
model.add(layers.Activation('softmax'))

In [31]:
# compiling the model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [32]:
# training the model
history = model.fit(X_train, Y_train,
          batch_size=128, epochs=20,
          verbose=2,
          validation_data=(X_test, Y_test))

Epoch 1/20
263/263 - 4s - loss: 0.3242 - accuracy: 0.9015 - val_loss: 0.1398 - val_accuracy: 0.9590
Epoch 2/20
263/263 - 4s - loss: 0.1248 - accuracy: 0.9626 - val_loss: 0.1029 - val_accuracy: 0.9699
Epoch 3/20
263/263 - 5s - loss: 0.0863 - accuracy: 0.9726 - val_loss: 0.0967 - val_accuracy: 0.9704
Epoch 4/20
263/263 - 4s - loss: 0.0632 - accuracy: 0.9801 - val_loss: 0.0881 - val_accuracy: 0.9733
Epoch 5/20
263/263 - 8s - loss: 0.0498 - accuracy: 0.9837 - val_loss: 0.0900 - val_accuracy: 0.9742
Epoch 6/20
263/263 - 5s - loss: 0.0415 - accuracy: 0.9860 - val_loss: 0.0941 - val_accuracy: 0.9713
Epoch 7/20
263/263 - 7s - loss: 0.0362 - accuracy: 0.9881 - val_loss: 0.0908 - val_accuracy: 0.9735
Epoch 8/20
263/263 - 6s - loss: 0.0286 - accuracy: 0.9904 - val_loss: 0.0990 - val_accuracy: 0.9754
Epoch 9/20
263/263 - 6s - loss: 0.0311 - accuracy: 0.9893 - val_loss: 0.0885 - val_accuracy: 0.9770
Epoch 10/20
263/263 - 6s - loss: 0.0236 - accuracy: 0.9917 - val_loss: 0.0922 - val_accuracy: 0.9787